before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    flags:
      - -trimpath      
    ldflags:
      - -s -w
dockers:
  - image_templates:
    - "costela/docker-etchosts:{{ .Tag }}"
    - "costela/docker-etchosts:{{ .Major }}"
    - "costela/docker-etchosts:{{ .Major }}.{{ .Minor }}"
    - "costela/docker-etchosts:latest"
archives:
    format: binary
checksum:
  algorithm: sha512
snapshot:
  name_template: "{{ incpatch .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  draft: true
  prerelease: auto

